### PR TITLE
support pagination and search by shorturl

### LINKED ISSUE #18: Support pagination
When a lot of shorts URL, the displayed table can freeze the browser, also is very slow to load.

### LINKED ISSUE #20: Support search short url
A filter by shortURL

### PR DESCRIPTION
**Pull request by xhit**
Fix #18
Fix #20

### CODE REVIEW

**Review by MatthewC — CHANGES_REQUESTED** [review]
Thanks for pointing that out!

However, the way you are handling the SQL query opens up the potential of an [SQL injection](https://www.w3schools.com/sql/sql_injection.asp). I'd recommend looking at [this](https://yourls.org/docs/development/database-queries#versions-173-and-up), and fixing the PR.

If I get time later today, I'll try helping out.

**Comment by xhit** [comment]
done 60375c5696fad6458a040a46320d46a077e60726

**Comment by xhit** [comment]
I added search by short url here d495a15a7e14dde0347fa4ae63c7576e13f30e95 that fixes #20 

Edit: any design changes should be handle by a frontend developer

Thanks for the plugin!

**Comment by MatthewC** [comment]
Really happy that you like the plugin!

I'm currently a bit busy, so I haven't had the chances to review the changes, but I promise I will soon!

**Review by MatthewC — APPROVED** [review]
Thanks again for these changes! Merging them into a separate branch for now to test it before merging it with main.

Thank you!

**Pull request merged**
